Repository CMPUT301F21T20/HabitTracker, pull requests merged in 2021-11, with the labels that each got.

#46 Habit Controller + Habit location removal
  app/src/main/java/com/example/habittracker/AddNewHabitActivity.java
  app/src/main/java/com/example/habittracker/classes/Habit.java
  app/src/main/java/com/example/habittracker/controllers/HabitController.java
  app/src/main/res/layout/activity_add_new_habit.xml
Labels: priority: high, complexity: medium, Needs Review

#50 HabitList + HabitList Controller
  .gitignore
  app/src/main/java/com/example/habittracker/AddNewHabitActivity.java
  app/src/main/java/com/example/habittracker/MainActivity.java
  app/src/main/java/com/example/habittracker/RegisterActivity.java
  app/src/main/java/com/example/habittracker/adapters/HabitListAdapter.java
  app/src/main/java/com/example/habittracker/classes/Habit.java
  app/src/main/java/com/example/habittracker/classes/HabitList.java
  app/src/main/java/com/example/habittracker/classes/User.java
  app/src/main/java/com/example/habittracker/controllers/HabitController.java
  app/src/main/java/com/example/habittracker/controllers/HabitListController.java
  app/src/test/java/com/example/habittracker/ExampleUnitTest.java
  app/src/test/java/com/example/habittracker/HabitListTest.java
  app/src/test/java/com/example/habittracker/UserTest.java
Labels: priority: high, Habits, complexity: medium, Complete by halfway checkpoint, Needs Review

#56 Update README.md
  README.md
Labels: Complete by halfway checkpoint

#60 Viewing habits and deleting habits
  app/src/main/java/com/example/habittracker/MainActivity.java
  app/src/main/java/com/example/habittracker/adapters/HabitListAdapter.java
  app/src/main/java/com/example/habittracker/classes/HabitList.java
  app/src/main/java/com/example/habittracker/controllers/HabitListController.java
  app/src/main/java/com/example/habittracker/interfaces/OnHabitListRetrieved.java
  app/src/main/java/com/example/habittracker/ui/home/HomeFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/habit_list_content.xml
  app/src/main/res/values/strings.xml
Labels: Complete by halfway checkpoint

#62 #61 Test issue fixed
  app/src/test/java/com/example/habittracker/HabitListTest.java
Labels: bug

#64 Added comments and changed variables name following convention.
  .gitignore
  app/src/main/java/com/example/habittracker/LoginActivity.java
  app/src/main/java/com/example/habittracker/MainActivity.java
  app/src/main/java/com/example/habittracker/RegisterActivity.java
  app/src/main/java/com/example/habittracker/ViewHabitActivity.java
  app/src/main/java/com/example/habittracker/adapters/HabitListAdapter.java
  app/src/main/java/com/example/habittracker/classes/Habit.java
  app/src/main/java/com/example/habittracker/classes/HabitList.java
  app/src/main/java/com/example/habittracker/classes/User.java
  app/src/main/java/com/example/habittracker/controllers/HabitController.java
  app/src/main/java/com/example/habittracker/controllers/HabitListController.java
Labels: documentation

#68 Adding Error Check for empty habit title, reason, and date when adding habit
  app/src/main/java/com/example/habittracker/AddNewHabitActivity.java
Labels: bug

#74 add edit habit feature
  app/src/main/java/com/example/habittracker/AddNewHabitActivity.java
  app/src/main/java/com/example/habittracker/AddNewHabitEventActivity.java
  app/src/main/java/com/example/habittracker/LoginActivity.java
  app/src/main/java/com/example/habittracker/MainActivity.java
  app/src/main/java/com/example/habittracker/RegisterActivity.java
  app/src/main/java/com/example/habittracker/ViewHabitActivity.java
  app/src/main/java/com/example/habittracker/classes/HabitEvent.java
  app/src/main/java/com/example/habittracker/ui/home/HomeFragment.java
  app/src/main/res/layout/activity_view_habit.xml
  app/src/main/res/layout/fragment_follower.xml
  app/src/main/res/layout/fragment_following_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: priority: medium, complexity: medium

#81 Vardan
  app/build.gradle
  app/src/main/java/com/example/habittracker/ui/profile/ProfileFragment.java
  app/src/main/res/drawable/ic_baseline_email_24.xml
  app/src/main/res/drawable/ic_baseline_phone_24.xml
  app/src/main/res/drawable/profile_bg.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/frag_profile.xml
  app/src/main/res/values/colors.xml
Labels: Profile

#82 Habit Event Scroll View fixed
  app/src/main/res/layout/activity_add_new_habit_event.xml
Labels: bug

#85 Update the location in mapsFragment
  app/src/main/java/com/example/habittracker/MapsFragment.java
  app/src/main/res/layout/activity_add_new_habit.xml
  app/src/main/res/layout/activity_add_new_habit_event.xml
  app/src/main/res/layout/activity_edit_habit.xml
  app/src/main/res/layout/activity_maps.xml
Labels: bug

#90 Final update for the photo feature of habit event
  app/build.gradle
  app/src/main/java/com/example/habittracker/AddNewHabitEventActivity.java
  app/src/main/java/com/example/habittracker/HabitsTodayFragment.java
  app/src/main/java/com/example/habittracker/HabitsTotalFragment.java
  app/src/main/java/com/example/habittracker/HabitsUnbrokenFragment.java
  app/src/main/java/com/example/habittracker/adapters/ViewPagerAdapter.java
  app/src/main/java/com/example/habittracker/ui/home/HomeFragment.java
  app/src/main/res/layout/activity_add_new_habit_event.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/fragment_habits_today.xml
  app/src/main/res/layout/fragment_habits_total.xml
  app/src/main/res/layout/fragment_habits_unbroken.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: priority: medium, complexity: medium

#101 HabitList Controller/document listener cleanup + HabitEventsList/HabitEventsController methods
  app/build.gradle
  app/src/main/java/com/example/habittracker/AddNewHabitActivity.java
  app/src/main/java/com/example/habittracker/AddNewHabitEventActivity.java
  app/src/main/java/com/example/habittracker/EditHabitActivity.java
  app/src/main/java/com/example/habittracker/HabitsTodayFragment.java
  app/src/main/java/com/example/habittracker/HabitsTotalFragment.java
  app/src/main/java/com/example/habittracker/ViewHabitActivity.java
  app/src/main/java/com/example/habittracker/adapters/HabitListAdapter.java
  app/src/main/java/com/example/habittracker/classes/HabitEvent.java
  app/src/main/java/com/example/habittracker/classes/HabitEventList.java
  app/src/main/java/com/example/habittracker/classes/HabitList.java
  app/src/main/java/com/example/habittracker/controllers/HabitController.java
  app/src/main/java/com/example/habittracker/controllers/HabitEventController.java
  app/src/main/java/com/example/habittracker/controllers/HabitEventsController.java
  app/src/main/java/com/example/habittracker/controllers/HabitListController.java
  app/src/main/java/com/example/habittracker/interfaces/OnHabitEventsRetrieved.java
  app/src/main/java/com/example/habittracker/ui/dashboard/DashboardFragment.java
Labels: priority: high, Habits, Habit Events, complexity: medium, Needs Review

#106 Request Initialization
  app/src/main/java/com/example/habittracker/RegisterActivity.java
  app/src/main/java/com/example/habittracker/classes/Request.java
Labels: work-in-progess

#108 UserList
  app/build.gradle
  app/src/main/java/com/example/habittracker/AddNewHabitActivity.java
  app/src/main/java/com/example/habittracker/MainActivity.java
  app/src/main/java/com/example/habittracker/adapters/UsersListAdapter.java
  app/src/main/java/com/example/habittracker/controllers/UsersListController.java
  app/src/main/java/com/example/habittracker/models/User.java
  app/src/main/java/com/example/habittracker/models/UsersList.java
  app/src/main/java/com/example/habittracker/ui/users/UsersFragment.java
  app/src/main/res/drawable/ic_baseline_person_search_24.xml
  app/src/main/res/layout/content_user_list.xml
  app/src/main/res/layout/fragment_users.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: complexity: high

#118 Search User Working
  app/src/main/java/com/example/habittracker/controllers/UsersListController.java
  app/src/main/java/com/example/habittracker/ui/users/UsersFragment.java
  app/src/main/res/layout/fragment_users.xml
Labels: enhancement

#129 update habit list delete button and user list UI
  app/src/main/java/com/example/habittracker/adapters/HabitListAdapter.java
  app/src/main/res/layout/activity_add_new_habit.xml
  app/src/main/res/layout/activity_edit_habit.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/content_habit_list.xml
  app/src/main/res/layout/content_habits_today.xml
  app/src/main/res/layout/content_habits_unbroken.xml
  app/src/main/res/layout/content_user_list.xml
  app/src/main/res/layout/fragment_habits_today.xml
  app/src/main/res/layout/fragment_habits_total.xml
  app/src/main/res/layout/fragment_users.xml
Labels: enhancement
